---
- name: Deploy VMs 
  hosts: localhost
  vars_files: vars.yml
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
  - name: deploy VMs
    local_action:
      module: vmware_guest
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: Datacenter
      datastore: datastore_6TB
      folder: otus_network
      template: "{{item.template}}"
      name: "{{item.name}}"
      hardware:
        memory_mb: "{{item.memory_mb}}"
      networks:
        - name: VMs11
          ip: "{{item.ip}}"
          netmask: "255.255.255.0"
          gateway: "10.100.11.254"
      customization:
        hostname: "{{item.hostname}}"
        dns_servers: [8.8.8.8]
      state: powered-on
      wait_for_ip_address: true
    with_items: "{{servers}}"
    register: deploy
    delegate_to: localhost

- name: configure mysql
  hosts: all
  become: true 
  gather_facts: false
  tasks:
  - name: install percona-server
    shell: "{{item}}"
    with_items:
      - systemctl stop firewalld
      - systemctl disable firewalld
      - yum -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      - percona-release setup ps-80 -y
      - yum -y install percona-server-server

- name: copy files to mysql1
  hosts: mysql1
  become: true
  gather_facts: false
  tasks:
  - name: copy to my.cnf
    copy:
      src: mysql1.cnf
      dest: /etc/my.cnf
  - name: copy dump
    copy:
      src: bet.dmp
      dest: /root/bet.dmp

- name: copy files to mysql2
  hosts: mysql2
  become: true
  gather_facts: false
  tasks:
  - name: copy to my.cnf
    copy:
      src: mysql2.cnf
      dest: /etc/my.cnf

- name: restart mysql
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: restart server
    shell: "{{item}}"
    with_items:
      - systemctl restart mysql
